"""
generate.py
-----------
Stage 5: combine retrieval with Groq llama-3.3-70b-versatile to produce a
grounded answer with source attribution.

Grounding is enforced two ways so it can't be hand-waved away by the LLM:
  1. The system prompt instructs the model to answer ONLY from the CONTEXT
     block of the latest user message, and otherwise reply with the exact
     no-info sentinel. The rule is stated as a hard requirement, not a
     suggestion.
  2. The Sources list is built in Python from the actual retrieval hits — it
     is NOT generated by the LLM. The model is told NOT to include sources,
     and the harness appends the deduplicated source list after the answer.
     This way the citations are programmatically guaranteed to be the chunks
     that were retrieved, not whatever the model felt like writing.
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from groq import Groq

from retrieve import retrieve

PROJECT_ROOT = Path(__file__).resolve().parent
load_dotenv(PROJECT_ROOT / ".env")

MODEL = "llama-3.3-70b-versatile"
DEFAULT_K = 5
NO_INFO_REPLY = "I don't have enough information on that."

CONTEXTUALIZE_PROMPT = """Given the chat history and the latest user question, rewrite the question so it stands alone without the chat history. Resolve pronouns and short follow-ups (e.g. "his comments", "what about her?", "more on that") into explicit references using names, courses, or topics from the prior turns.

Rules:
- Output ONLY the rewritten question. No preamble, no explanation, no quotes.
- If the question already stands alone, return it unchanged.
- Do not answer the question.
- Keep the phrasing concise and natural.
"""

SYSTEM_PROMPT = f"""You are an unofficial guide to the CU Boulder Computer Science department, drawing on student reviews, Reddit posts, course ratings, and grade data.

You MUST follow these rules without exception:

1. Answer ONLY using information found in the CONTEXT block of the latest user message. Do not use prior knowledge of CU Boulder, professors, courses, or any other fact not present in the CONTEXT.
2. If the CONTEXT does not contain enough information to answer the question, reply with EXACTLY this sentence and nothing else: "{NO_INFO_REPLY}"
3. Do not invent professors, courses, numbers, dates, grades, GPAs, or quotes. If a detail is not literally in the CONTEXT, leave it out.
4. Do NOT include a sources list, citations, footnotes, "[1]" markers, or URLs in your answer. The system appends sources automatically after your reply; do not duplicate them.
5. Keep your answer concise (roughly under 150 words) and paraphrase the retrieved snippets faithfully. Prefer direct, plain language.
"""


def _format_context(hits):
    lines = []
    for i, h in enumerate(hits, 1):
        lines.append(f"[{i}] SOURCE: {h['source']}")
        lines.append(h["text"].strip())
        lines.append("")
    return "\n".join(lines).strip()


def _unique_sources(hits):
    seen = []
    for h in hits:
        s = h.get("source") or ""
        if s and s not in seen:
            seen.append(s)
    return seen


def _contextualize_query(query, chat_history, client):
    """Rewrite a follow-up question into a standalone one using prior turns.

    Returns the rewritten query, or the original if no rewrite is needed.
    """
    if not chat_history:
        return query
    messages = [{"role": "system", "content": CONTEXTUALIZE_PROMPT}]
    for turn in chat_history:
        role = turn.get("role")
        content = turn.get("content")
        if role in {"user", "assistant"} and content:
            messages.append({"role": role, "content": content})
    messages.append({"role": "user", "content": query})
    completion = client.chat.completions.create(
        model=MODEL,
        messages=messages,
        temperature=0,
        max_tokens=128,
    )
    rewritten = completion.choices[0].message.content.strip().strip('"')
    return rewritten or query


def generate_answer(query, chat_history=None, k=DEFAULT_K):
    """Retrieve, generate, and return (bare_answer, sources_block, hits).

    `chat_history` is an optional list of {"role": ..., "content": ...} dicts
    representing prior turns. If history is present, the query is first
    rewritten into a standalone question so retrieval uses the conversation's
    actual subject (e.g. "What are some comments?" after a CSCI 3104 question
    becomes "What are some comments about CSCI 3104 professors?"). The Sources
    block is only built when the model actually answered (not the no-info
    sentinel).
    """
    client = Groq(api_key=os.environ["GROQ_API_KEY"])
    search_query = _contextualize_query(query, chat_history, client)
    hits = retrieve(search_query, k=k)
    context = _format_context(hits)
    user_msg = f"CONTEXT:\n{context}\n\nQUESTION: {query}"

    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    for turn in (chat_history or []):
        role = turn.get("role")
        content = turn.get("content")
        if role in {"user", "assistant"} and content:
            messages.append({"role": role, "content": content})
    messages.append({"role": "user", "content": user_msg})

    completion = client.chat.completions.create(
        model=MODEL,
        messages=messages,
        temperature=0.2,
        max_tokens=512,
    )
    bare_answer = completion.choices[0].message.content.strip()

    # If the model used the no-info sentinel, don't tack on misleading sources.
    if bare_answer.lower().startswith("i don't have enough information"):
        return bare_answer, "", hits

    sources = _unique_sources(hits)
    sources_block = "\n".join(f"- {s}" for s in sources)
    return bare_answer, sources_block, hits


def format_full_answer(bare_answer, sources_block):
    if not sources_block:
        return bare_answer
    return f"{bare_answer}\n\n**Sources:**\n{sources_block}"


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="One-shot grounded Q&A test.")
    ap.add_argument("query")
    ap.add_argument("-k", type=int, default=DEFAULT_K)
    args = ap.parse_args()
    bare, src, _hits = generate_answer(args.query, k=args.k)
    print(format_full_answer(bare, src))
